FROM pytorch/pytorch:2.2.0-cuda12.1-cudnn8-runtime

# Working directory
WORKDIR /app

# Copy the training script
COPY train.py /app/

# Install optional extras for nicer logs (tqdm, etc.)
RUN pip install --no-cache-dir pillow numpy torchvision matplotlib tqdm torchmetrics

# Run local training
CMD ["python", "train.py"]
